"""HTML report builder for SuperScrape visual intelligence."""

from __future__ import annotations

import base64
import html as html_lib
import logging
from collections.abc import Callable
from datetime import datetime, timezone
from typing import TYPE_CHECKING

import httpx

if TYPE_CHECKING:
    from superscrape.output.models import CategoryVisualReport, ImageAnalysis, ScrapedItem

from api.models.api_models import Language

logger = logging.getLogger(__name__)

# ── Platform Display Names ────────────────────────────────────────────────────

_PLATFORM_NAMES_EN = {
    "amazon": "Amazon",
    "shopee": "Shopee",
    "tiktok_shop": "TikTok Shop",
    "instagram": "Instagram",
    "pinterest": "Pinterest",
    "tiktok": "TikTok",
    "xiaohongshu": "Xiaohongshu",
    "lazada": "Lazada",
    "temu": "Temu",
    "ebay": "eBay",
    "walmart": "Walmart",
    "etsy": "Etsy",
    "shopify": "Shopify",
}

_PLATFORM_NAMES_ZH = {
    "amazon": "亚马逊",
    "shopee": "虾皮",
    "tiktok_shop": "TikTok 小店",
    "instagram": "Instagram",
    "pinterest": "Pinterest",
    "tiktok": "TikTok",
    "xiaohongshu": "小红书",
    "lazada": "Lazada",
    "temu": "Temu",
    "ebay": "eBay",
    "walmart": "沃尔玛",
    "etsy": "Etsy",
    "shopify": "Shopify",
}

# ── Label Sets ────────────────────────────────────────────────────────────────

_LABELS_EN = {
    "title": "{platform} Visual Intelligence Report",
    "subtitle": "Powered by SuperScrape",
    "generated": "Generated",
    "products_analyzed": "Products Analyzed",
    "images_analyzed": "Images Analyzed",
    "with_person": "With Person / Model",
    "with_text": "With Text Overlay",
    "image_type_dist": "Image Type Distribution",
    "angle_dist": "Camera Angle Distribution",
    "bg_dist": "Background Distribution",
    "recommendations": "Recommendations",
    "top_products": "Competitive Image Grid",
    "lifestyle_images": "AI-Generated Lifestyle Images",
    "exec_summary": "Executive Summary",
    "key_findings": "Key Findings",
    "action_items": "What You Should Do",
    "visual_score": "Category Visual Score",
    "col_rank": "#",
    "col_id": "ID",
    "col_title": "Title",
    "col_price": "Price",
    "col_rating": "Rating",
    "col_reviews": "Reviews",
    "col_type": "Image Type",
    "col_angle": "Angle",
    "col_person": "Person?",
    "col_text": "Text?",
    "yes": "Yes",
    "no": "No",
    "footer": "Generated by SuperScrape — Visual Intelligence",
}

_LABELS_ZH = {
    "title": "{platform}视觉情报报告",
    "subtitle": "Powered by SuperScrape",
    "generated": "生成时间",
    "products_analyzed": "分析产品数",
    "images_analyzed": "分析图片数",
    "with_person": "含人物 / 模特",
    "with_text": "含文字覆层",
    "image_type_dist": "图片类型分布",
    "angle_dist": "拍摄角度分布",
    "bg_dist": "背景风格分布",
    "recommendations": "优化建议",
    "top_products": "竞品图片对比",
    "lifestyle_images": "AI 生成生活场景图",
    "exec_summary": "摘要总结",
    "key_findings": "核心发现",
    "action_items": "你应该做什么",
    "visual_score": "品类视觉评分",
    "col_rank": "#",
    "col_id": "ID",
    "col_title": "标题",
    "col_price": "价格",
    "col_rating": "评分",
    "col_reviews": "评价数",
    "col_type": "图片类型",
    "col_angle": "角度",
    "col_person": "含人?",
    "col_text": "含文字?",
    "yes": "是",
    "no": "否",
    "footer": "由 SuperScrape 生成 — 视觉情报引擎",
}

# ── Product URL builders per platform ─────────────────────────────────────────

_PRODUCT_URL_BUILDERS: dict[str, Callable[[str], str]] = {
    "amazon": lambda item_id: f"https://www.amazon.com/dp/{item_id}",
    "walmart": lambda item_id: f"https://www.walmart.com/ip/{item_id}",
    "ebay": lambda item_id: f"https://www.ebay.com/itm/{item_id}",
    "etsy": lambda item_id: f"https://www.etsy.com/listing/{item_id}",
    "shopee": lambda item_id: f"https://shopee.sg/product/{item_id}",
    "tiktok_shop": lambda item_id: f"https://shop.tiktok.com/product/{item_id}",
}


def _product_link(platform: str, item_id: str, url: str) -> str:
    """Return the best product URL -- prefer stored url, fallback to builder."""
    if url:
        return url
    builder = _PRODUCT_URL_BUILDERS.get(platform)
    if builder:
        return builder(item_id)
    return ""


def _fetch_image_b64(url: str) -> str | None:
    """Fetch an image from a URL and return its base64 data-URI, or None on failure."""
    try:
        with httpx.Client(timeout=15.0, follow_redirects=True) as client:
            resp = client.get(url, headers={"User-Agent": "Mozilla/5.0"})
            resp.raise_for_status()
        content_type = resp.headers.get("content-type", "image/jpeg").split(";")[0].strip()
        b64 = base64.b64encode(resp.content).decode()
        return f"data:{content_type};base64,{b64}"
    except Exception as exc:
        logger.warning("Failed to fetch image for embedding: %s — %s", url, exc)
        return None


# ── Score Computation ─────────────────────────────────────────────────────────

def _visual_score_letter(report: "CategoryVisualReport") -> tuple[str, str, str]:
    """Compute a visual score letter (A-D) based on report data.

    Returns (letter, color, description).
    """
    score = 0
    total = report.total_images
    if total == 0:
        return ("D", "#EF4444", "Insufficient data")

    # Diversity of image types (more types = better)
    n_types = len(report.image_type_distribution)
    if n_types >= 5:
        score += 3
    elif n_types >= 3:
        score += 2
    elif n_types >= 2:
        score += 1

    # Person presence (15-60% is ideal)
    person = report.has_person_ratio
    if 15 <= person <= 60:
        score += 2
    elif person > 0:
        score += 1

    # Text overlay usage (20-70% is normal)
    text = report.has_text_ratio
    if 20 <= text <= 70:
        score += 2
    elif text > 0:
        score += 1

    # Angle diversity
    n_angles = len(report.angle_distribution)
    if n_angles >= 4:
        score += 2
    elif n_angles >= 2:
        score += 1

    # Products analyzed
    if report.total_products >= 10:
        score += 1

    # Map to letter grade
    if score >= 9:
        return ("A", "#10B981", "Strong visual competition")
    elif score >= 6:
        return ("B", "#2563EB", "Moderate visual competition")
    elif score >= 3:
        return ("C", "#F59E0B", "Weak visual standards")
    else:
        return ("D", "#EF4444", "Minimal visual effort")


def _generate_executive_findings(
    report: "CategoryVisualReport",
    lang: str = "en",
) -> list[str]:
    """Generate 3 key findings for the executive summary."""
    findings: list[str] = []

    # Finding 1: Dominant image type
    if report.image_type_distribution:
        top_type = max(report.image_type_distribution, key=report.image_type_distribution.get)
        top_pct = report.image_type_distribution[top_type]
        if lang == "zh":
            findings.append(
                f"主导图片类型是 <strong>{top_type}</strong>（占 {top_pct:.0f}%）"
                "— 这是该品类的视觉基准线"
            )
        else:
            findings.append(
                f"<strong>{top_type}</strong> dominates at {top_pct:.0f}% "
                "— this is the category visual baseline"
            )

    # Finding 2: Person/model usage
    person_pct = report.has_person_ratio
    if lang == "zh":
        if person_pct > 40:
            findings.append(
                f"<strong>{person_pct:.0f}%</strong> 的竞品使用真人模特 — 你也需要人物展示"
            )
        elif person_pct < 15:
            findings.append(
                f"仅 <strong>{person_pct:.0f}%</strong> 使用人物 — 添加模特可成为差异化优势"
            )
        else:
            findings.append(
                f"<strong>{person_pct:.0f}%</strong> 的产品展示人物 — 行业中等水平"
            )
    else:
        if person_pct > 40:
            findings.append(
                f"<strong>{person_pct:.0f}%</strong> of competitors use people/models "
                "— you need human presence too"
            )
        elif person_pct < 15:
            findings.append(
                f"Only <strong>{person_pct:.0f}%</strong> show people "
                "— adding a model could differentiate you"
            )
        else:
            findings.append(
                f"<strong>{person_pct:.0f}%</strong> of products show people "
                "— moderate industry standard"
            )

    # Finding 3: Text overlay
    text_pct = report.has_text_ratio
    if lang == "zh":
        if text_pct > 50:
            findings.append(
                f"<strong>{text_pct:.0f}%</strong> 使用文字标注 — 信息图/功能标注是标配"
            )
        else:
            findings.append(
                f"仅 <strong>{text_pct:.0f}%</strong> 使用文字覆层 — 添加卖点标注可脱颖而出"
            )
    else:
        if text_pct > 50:
            findings.append(
                f"<strong>{text_pct:.0f}%</strong> use text overlays "
                "— callouts and feature badges are standard"
            )
        else:
            findings.append(
                f"Only <strong>{text_pct:.0f}%</strong> use text overlays "
                "— adding feature callouts could give you an edge"
            )

    return findings


# ── HTML Section Builders ─────────────────────────────────────────────────────

def _bar_html(pct: float, color: str = "#2563EB") -> str:
    """Render a progress bar as inline HTML."""
    width = min(max(pct, 0), 100)
    return (
        f'<div class="bar-wrap">'
        f'<div class="bar-fill" style="width:{width:.1f}%;background:{color}"></div>'
        f'<span class="bar-label">{pct:.1f}%</span>'
        f"</div>"
    )


def _dist_table_rows(dist: dict[str, float]) -> str:
    rows = []
    for label, pct in sorted(dist.items(), key=lambda x: -x[1]):
        # Color code: green for top, blue for mid, gray for low
        if pct >= 30:
            color = "#10B981"
        elif pct >= 15:
            color = "#2563EB"
        else:
            color = "#94A3B8"
        rows.append(
            f"<tr><td>{html_lib.escape(str(label))}</td><td>{_bar_html(pct, color)}</td></tr>"
        )
    return "\n".join(rows)


def _build_exec_summary(
    report: "CategoryVisualReport",
    lbl: dict[str, str],
    lang: str,
) -> str:
    """Build the executive summary section with score + key findings."""
    letter, color, desc = _visual_score_letter(report)
    findings = _generate_executive_findings(report, lang)

    findings_html = "\n".join(
        f'<div class="finding-item"><span class="finding-bullet">&#x2022;</span>{f}</div>'
        for f in findings
    )

    return f"""
    <div class="exec-summary">
      <div class="exec-left">
        <h2>{lbl['exec_summary']}</h2>
        <div class="score-badge" style="border-color:{color}">
          <div class="score-letter" style="color:{color}">{letter}</div>
          <div class="score-desc">{desc}</div>
        </div>
      </div>
      <div class="exec-right">
        <h3>{lbl['key_findings']}</h3>
        <div class="findings-list">{findings_html}</div>
      </div>
    </div>
    """


def _build_kpi_cards(
    report: "CategoryVisualReport",
    lbl: dict[str, str],
) -> str:
    """Build the KPI cards row."""
    return f"""
    <div class="kpi-grid">
      <div class="kpi-card">
        <div class="kpi-value">{report.total_products}</div>
        <div class="kpi-label">{lbl['products_analyzed']}</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-value">{report.total_images}</div>
        <div class="kpi-label">{lbl['images_analyzed']}</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-value">{report.has_person_ratio:.1f}%</div>
        <div class="kpi-label">{lbl['with_person']}</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-value">{report.has_text_ratio:.1f}%</div>
        <div class="kpi-label">{lbl['with_text']}</div>
      </div>
    </div>
    """


def _build_dist_section(
    report: "CategoryVisualReport",
    lbl: dict[str, str],
) -> str:
    """Build the 3-column distribution tables section."""
    return f"""
    <div class="section-grid">
      <div class="card">
        <h2>{lbl['image_type_dist']}</h2>
        <table class="dist-table">
          {_dist_table_rows(report.image_type_distribution)}
        </table>
      </div>
      <div class="card">
        <h2>{lbl['angle_dist']}</h2>
        <table class="dist-table">
          {_dist_table_rows(report.angle_distribution)}
        </table>
      </div>
      <div class="card">
        <h2>{lbl['bg_dist']}</h2>
        <table class="dist-table">
          {_dist_table_rows(report.background_distribution)}
        </table>
      </div>
    </div>
    """


def _build_recommendations(
    report: "CategoryVisualReport",
    lbl: dict[str, str],
) -> str:
    """Build the recommendations section with priority tags."""
    if not report.recommendations:
        return ""

    items = []
    for i, rec in enumerate(report.recommendations):
        priority = "quick-win" if i < 2 else "strategic"
        tag_label = "Quick Win" if priority == "quick-win" else "Strategic"
        tag_color = "#10B981" if priority == "quick-win" else "#6366F1"
        items.append(
            f'<li class="rec-item">'
            f'<span class="rec-tag" style="background:{tag_color}10;color:{tag_color}">{tag_label}</span>'
            f'{html_lib.escape(str(rec))}'
            f"</li>"
        )

    return f"""
    <div class="card section-break">
      <h2>{lbl['recommendations']}</h2>
      <ol class="rec-list">{''.join(items)}</ol>
    </div>
    """


def _build_product_grid(
    report: "CategoryVisualReport",
    products: list["ScrapedItem"],
    lbl: dict[str, str],
    platform: str,
) -> str:
    """Build the competitive image grid — large product cards with analysis tags."""
    if not report.product_analyses:
        return ""

    id_to_product = {p.item_id: p for p in products}
    cards_html = []

    for i, pa in enumerate(report.product_analyses):
        item_id = pa.get("item_id", pa.get("asin", ""))
        product = id_to_product.get(item_id)
        product_url = _product_link(platform, item_id, pa.get("url", ""))

        # Fetch and embed main image
        img_html = '<div class="card-img-placeholder">No Image</div>'
        if product and product.main_image_url:
            b64 = _fetch_image_b64(product.main_image_url)
            if b64:
                img_html = f'<img src="{b64}" class="card-img" alt="{pa["title"][:40]}">'

        # Analysis tags
        type_tag = pa.get("main_image_type", "unknown")
        angle_tag = pa.get("main_image_angle", "unknown")
        person_cls = "tag-yes" if pa.get("has_person") else "tag-no"
        text_cls = "tag-yes" if pa.get("has_text") else "tag-no"
        person_label = lbl["yes"] if pa.get("has_person") else lbl["no"]
        text_label = lbl["yes"] if pa.get("has_text") else lbl["no"]

        title_link = (
            f'<a href="{product_url}" target="_blank" class="card-title">'
            f'{html_lib.escape(str(pa["title"][:55]))}</a>'
            if product_url
            else f'<span class="card-title">{html_lib.escape(str(pa["title"][:55]))}</span>'
        )

        price_str = html_lib.escape(str(pa.get("price", "")))
        rating_str = html_lib.escape(str(pa.get("rating", "")))
        reviews_str = html_lib.escape(str(pa.get("reviews", "")))

        cards_html.append(f"""
        <div class="product-card">
          <div class="card-rank">#{i + 1}</div>
          <div class="card-image-wrap">{img_html}</div>
          <div class="card-info">
            {title_link}
            <div class="card-meta">
              {f'<span class="meta-price">{price_str}</span>' if price_str else ''}
              {f'<span class="meta-rating">★ {rating_str}</span>' if rating_str else ''}
              {f'<span class="meta-reviews">{reviews_str} reviews</span>' if reviews_str else ''}
            </div>
            <div class="card-tags">
              <span class="tag tag-type">{type_tag}</span>
              <span class="tag tag-angle">{angle_tag}</span>
              <span class="tag {person_cls}">Person: {person_label}</span>
              <span class="tag {text_cls}">Text: {text_label}</span>
            </div>
          </div>
        </div>""")

    return f"""
    <div class="section-break">
      <h2 class="section-title">{lbl['top_products']}</h2>
      <div class="product-grid">
        {''.join(cards_html)}
      </div>
    </div>
    """


def _build_lifestyle_section(
    lifestyle_images: list[str],
    lbl: dict[str, str],
) -> str:
    """Build the AI lifestyle images section."""
    if not lifestyle_images:
        return ""

    imgs_html = []
    for url in lifestyle_images:
        b64 = _fetch_image_b64(url)
        src = b64 if b64 else url
        imgs_html.append(f'<img src="{src}" class="lifestyle-img" alt="lifestyle">')

    return f"""
    <div class="card section-break">
      <h2>{lbl['lifestyle_images']}</h2>
      <div class="lifestyle-grid">{''.join(imgs_html)}</div>
    </div>
    """


# ── Main Builder ──────────────────────────────────────────────────────────────

def build_html_report(
    report: "CategoryVisualReport",
    products: list["ScrapedItem"],
    analyses: list["ImageAnalysis"],
    lifestyle_images: list[str],
    language: Language = Language.en,
) -> str:
    """Build a self-contained, bilingual HTML report.

    All product images are base64-embedded for PDF compatibility.
    Designed for Playwright Chromium PDF export with full CSS Grid support.
    """
    lang = "zh" if language == Language.zh else "en"
    lbl = _LABELS_ZH if lang == "zh" else _LABELS_EN
    platform = report.platform or "amazon"

    if lang == "zh":
        platform_name = _PLATFORM_NAMES_ZH.get(platform, platform.title())
    else:
        platform_name = _PLATFORM_NAMES_EN.get(platform, platform.title())

    title = lbl["title"].format(platform=platform_name)
    now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Build all sections
    exec_summary = _build_exec_summary(report, lbl, lang)
    kpi_cards = _build_kpi_cards(report, lbl)
    dist_section = _build_dist_section(report, lbl)
    rec_section = _build_recommendations(report, lbl)
    product_grid = _build_product_grid(report, products, lbl, platform)
    lifestyle_section = _build_lifestyle_section(lifestyle_images, lbl)

    css = _get_css()

    return f"""<!DOCTYPE html>
<html lang="{lang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title} — {report.keyword}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>{css}</style>
</head>
<body>
  <div class="page">
    <!-- Header -->
    <header class="site-header">
      <div class="header-left">
        <div class="header-brand">SuperScrape</div>
        <div class="header-tagline">Visual Intelligence</div>
      </div>
      <div class="header-right">
        <div class="header-meta">{lbl['subtitle']}</div>
      </div>
    </header>

    <!-- Report Title -->
    <div class="report-header">
      <h1 class="report-title">{title}</h1>
      <p class="report-keyword">"{html_lib.escape(report.keyword)}"</p>
      <p class="report-date">{lbl['generated']}: {now}</p>
    </div>

    <!-- Executive Summary -->
    {exec_summary}

    <!-- KPI Cards -->
    {kpi_cards}

    <!-- Distribution Charts -->
    {dist_section}

    <!-- Recommendations -->
    {rec_section}

    <!-- Competitive Image Grid -->
    {product_grid}

    <!-- Lifestyle Images -->
    {lifestyle_section}

    <!-- Footer -->
    <footer class="site-footer">{lbl['footer']}</footer>
  </div>
</body>
</html>"""


# ── CSS ───────────────────────────────────────────────────────────────────────

def _get_css() -> str:
    return """
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
      background: #F8F9FA;
      color: #111827;
      font-size: 13px;
      line-height: 1.6;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    .page {
      max-width: 1100px;
      margin: 0 auto;
      padding: 20px 16px 40px;
    }

    /* ── Header ── */
    .site-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 14px 0;
      border-bottom: 3px solid #2563EB;
      margin-bottom: 28px;
    }
    .header-left { display: flex; align-items: baseline; gap: 10px; }
    .header-brand {
      font-weight: 700;
      font-size: 20px;
      color: #2563EB;
      letter-spacing: -0.5px;
    }
    .header-tagline {
      font-size: 12px;
      font-weight: 500;
      color: #6B7280;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    .header-right { text-align: right; }
    .header-meta { font-size: 11px; color: #9CA3AF; }

    /* ── Report intro ── */
    .report-header { margin-bottom: 24px; }
    .report-title { font-size: 26px; font-weight: 700; letter-spacing: -0.5px; color: #111827; }
    .report-keyword {
      font-size: 18px;
      color: #2563EB;
      font-weight: 600;
      margin-top: 4px;
    }
    .report-date { color: #9CA3AF; font-size: 12px; margin-top: 2px; }

    /* ── Executive Summary ── */
    .exec-summary {
      display: grid;
      grid-template-columns: 240px 1fr;
      gap: 24px;
      background: #fff;
      border: 1px solid #E5E7EB;
      border-radius: 12px;
      padding: 24px;
      margin-bottom: 24px;
    }
    .exec-left h2 { font-size: 14px; font-weight: 600; margin-bottom: 16px; color: #374151; }
    .exec-right h3 { font-size: 13px; font-weight: 600; margin-bottom: 12px; color: #374151; }

    .score-badge {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      width: 120px;
      height: 120px;
      border-radius: 50%;
      border: 4px solid;
      margin: 0 auto;
    }
    .score-letter { font-size: 48px; font-weight: 700; line-height: 1; }
    .score-desc { font-size: 10px; font-weight: 500; color: #6B7280; margin-top: 4px; text-align: center; }

    .findings-list { display: flex; flex-direction: column; gap: 10px; }
    .finding-item {
      display: flex;
      align-items: flex-start;
      gap: 8px;
      font-size: 13px;
      color: #374151;
      line-height: 1.6;
    }
    .finding-bullet { color: #2563EB; font-size: 18px; line-height: 1.3; flex-shrink: 0; }

    /* ── KPI Grid ── */
    .kpi-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 12px;
      margin-bottom: 24px;
    }
    .kpi-card {
      background: #fff;
      border-radius: 10px;
      padding: 16px;
      border: 1px solid #E5E7EB;
      text-align: center;
    }
    .kpi-value { font-size: 28px; font-weight: 700; color: #2563EB; }
    .kpi-label {
      font-size: 10px;
      color: #6B7280;
      margin-top: 2px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }

    /* ── Cards ── */
    .card {
      background: #fff;
      border-radius: 12px;
      border: 1px solid #E5E7EB;
      padding: 20px;
      margin-bottom: 20px;
    }
    .card h2 {
      font-size: 14px;
      font-weight: 600;
      margin-bottom: 14px;
      color: #111827;
    }

    /* ── Section grid (3 dist tables) ── */
    .section-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 12px;
      margin-bottom: 20px;
    }

    /* ── Distribution tables ── */
    .dist-table { width: 100%; border-collapse: collapse; }
    .dist-table td { padding: 5px 4px; font-size: 12px; vertical-align: middle; }
    .dist-table td:first-child { width: 38%; font-weight: 500; color: #374151; }

    /* ── Progress bars ── */
    .bar-wrap {
      display: flex;
      align-items: center;
      gap: 8px;
    }
    .bar-fill {
      height: 8px;
      border-radius: 4px;
      min-width: 2px;
    }
    .bar-label { font-size: 11px; color: #6B7280; white-space: nowrap; }

    /* ── Recommendations ── */
    .rec-list { padding-left: 0; list-style: none; }
    .rec-item {
      display: flex;
      align-items: flex-start;
      gap: 10px;
      margin-bottom: 12px;
      color: #374151;
      line-height: 1.7;
      font-size: 13px;
    }
    .rec-tag {
      flex-shrink: 0;
      font-size: 10px;
      font-weight: 600;
      padding: 2px 8px;
      border-radius: 4px;
      text-transform: uppercase;
      letter-spacing: 0.3px;
      margin-top: 2px;
    }

    /* ── Section title (outside card) ── */
    .section-title {
      font-size: 16px;
      font-weight: 700;
      margin-bottom: 16px;
      color: #111827;
    }

    /* ── Product Grid (Image Cards) ── */
    .product-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 16px;
    }

    .product-card {
      position: relative;
      background: #fff;
      border: 1px solid #E5E7EB;
      border-radius: 12px;
      overflow: hidden;
      display: flex;
      flex-direction: column;
    }
    .card-rank {
      position: absolute;
      top: 8px;
      left: 8px;
      background: rgba(0,0,0,0.7);
      color: #fff;
      font-size: 11px;
      font-weight: 700;
      padding: 2px 8px;
      border-radius: 6px;
      z-index: 1;
    }
    .card-image-wrap {
      width: 100%;
      height: 200px;
      background: #F9FAFB;
      display: flex;
      align-items: center;
      justify-content: center;
      overflow: hidden;
    }
    .card-img {
      width: 100%;
      height: 100%;
      object-fit: contain;
    }
    .card-img-placeholder {
      color: #9CA3AF;
      font-size: 12px;
    }
    .card-info {
      padding: 12px;
      display: flex;
      flex-direction: column;
      gap: 6px;
    }
    .card-title {
      font-size: 12px;
      font-weight: 600;
      color: #111827;
      text-decoration: none;
      line-height: 1.4;
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical;
      overflow: hidden;
    }
    .card-title:hover { color: #2563EB; }
    .card-meta {
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
      font-size: 11px;
      color: #6B7280;
    }
    .meta-price { font-weight: 600; color: #111827; }
    .meta-rating { color: #F59E0B; }
    .card-tags {
      display: flex;
      gap: 4px;
      flex-wrap: wrap;
    }
    .tag {
      font-size: 9px;
      font-weight: 600;
      padding: 2px 6px;
      border-radius: 4px;
      text-transform: uppercase;
      letter-spacing: 0.3px;
    }
    .tag-type { background: #EFF6FF; color: #2563EB; }
    .tag-angle { background: #F0FDF4; color: #16A34A; }
    .tag-yes { background: #FEF3C7; color: #D97706; }
    .tag-no { background: #F3F4F6; color: #9CA3AF; }

    /* ── Lifestyle images ── */
    .lifestyle-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
      gap: 16px;
    }
    .lifestyle-img {
      width: 100%;
      height: 200px;
      object-fit: cover;
      border-radius: 8px;
      border: 1px solid #E5E7EB;
    }

    /* ── Footer ── */
    .site-footer {
      text-align: center;
      font-size: 11px;
      color: #9CA3AF;
      margin-top: 40px;
      padding-top: 14px;
      border-top: 1px solid #E5E7EB;
    }

    /* ── Print / PDF Styles ── */
    .section-break { break-before: auto; }

    @media print {
      body { background: white; font-size: 11px; }
      .page { padding: 0; max-width: 100%; }

      /* Preserve grid layouts */
      .kpi-grid { grid-template-columns: repeat(4, 1fr) !important; }
      .section-grid { grid-template-columns: repeat(3, 1fr) !important; }
      .exec-summary { grid-template-columns: 200px 1fr !important; }
      .product-grid { grid-template-columns: repeat(2, 1fr) !important; }

      /* Prevent page breaks inside cards */
      .card, .product-card, .exec-summary, .kpi-grid {
        break-inside: avoid;
      }
      .section-break {
        break-before: page;
      }

      /* Ensure background colors print */
      * {
        -webkit-print-color-adjust: exact !important;
        print-color-adjust: exact !important;
      }
    }
    """
